[project]
name = "sim-broker"
version = "0.0.1"
description = "Simulated broker-dealer environment"
authors = [{ name = "Miles Wright" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "pydantic",
    "rich",
    "PyYAML",
    "kafka-python (>=2.1.5,<3.0.0)",
    "pyarrow (>=19.0.1,<20.0.0)",
    "fsspec (>=2025.3.2,<2026.0.0)",
    "bytewax (>=0.21.1,<0.22.0)",
]


[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

# tell setuptools exactly which package(s) to include
[tool.setuptools]
packages = ["sim_broker"]

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = [
  ".venv",
  "infra",
  "lake",
  "pgdata",
  "sim_broker.egg-info",
]